import './globals.css';
import { Geist, Geist_Mono } from 'next/font/google';
//import Navigation from '../../components/navigation';
//import Footer from '../../components/footer';
// 네비게이션이랑 푸터 잠시 주석 처리 2025/4/1

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata = {
  title: 'Create Next',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  // tsx 변환
  return (
    <html lang="ko">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {/*         <Navigation />  */}
        {children}
        {/*         <Footer /> */}
      </body>
    </html>
  );
}

/*
// 최상위 app의 layout은 "모든 컴포넌트" 에 UI을 할당한다.
// 예를 들어 항상 쓰이는 상단의 네비게이션이나 footer, 고정 버튼
// 등등의 공통 UI가 필요할시 사용한다.
*/
